-- NOTE: This file is not used by the application.
--
-- The real schema is created at runtime by SqlFlightRepository.initialize()
-- (src/main/java/com/richi/repository/SqlFlightRepository.java), which emits
-- dialect-specific DDL for the configured db.type (SQLite by default, MySQL
-- optionally) and migrates existing databases via ALTER TABLE ADD COLUMN.
--
-- Edit that method, not this file, when changing the flights table.
